canonical/charmed-kubeflow-chisme

- src/k8s_resource_handler/kubernetes/_kubernetes_resource_handler.py
- src/k8s_resource_handler/lightkube/__init__.py
- tests/test_kubernetes.py
Changes KRH api from needing context/template_file factories to instead taking static values for context and template_files.  These inputs can be lazily loaded (a KRH object can be instantiated without defining them), allowing a user to create the object in a charm __init__ but later add context based on a hook's logic.
> refactor KubernetesResourceHandler api

- src/charmed_kubeflow_chisme/lightkube/batch/_many.py
- tests/test_lightkube.py
Client.delete() expects a resource type, not an instantiated resource.  This fix updates delete_many to
> fix: delete_many passing incorrect arg to client

- setup.cfg
- src/charmed_kubeflow_chisme/bundle/__init__.py
- src/charmed_kubeflow_chisme/bundle/_bundle.py
- src/charmed_kubeflow_chisme/juju/__init__.py
- src/charmed_kubeflow_chisme/juju/_juju.py
This PR adds tools to make it easier to interact with charm bundles and the Juju CLI.  
Bundle class adds things like loading bundles from yaml, comparing bundles, diffing bundles.  Also included is the get_newest_charm_revision() helper, which retrieves from `juju info` cli command what the newest charm revision is for a charm in a particular channel.
Juju class and helpers add some convenience functions and structure around calling the juju cli
> feat: add tools for interacting with bundles and juju CLI

- src/charmed_kubeflow_chisme/kubernetes/_kubernetes_resource_handler.py
- tox.ini
Exposes `lightkube.load_all_yaml()`'s `create_resources_for_crds` argument as `KubernetesResourceHandler.render_manifests(create_resources_for_crds=True)`.  This lets users of the KubernetesResourceHandler automatically generate generic resources as they load new CRDs.
> feat: enable auto-generation of generic resources

- setup.cfg
There is a dependency in deepdiff (orjson) which requires rust to be present in the charm when installing pip packages, causing an error if it's not. To avoid the error, we can pin deepdiff to version 6.2.1 which has a dependency tree that does not require rust.
Fixes #42
> fix: pin deepdiff==6.2.1 to avoid build time error

- setup.cfg
Previously we pinned to exactly `deepdiff==6.2.1` to avoid compile issues, but really we can accept an older version as well.  Our only constraint is nothing newer than 6.2.1
> fix: loosen pinning of `deepdiff`

- src/charmed_kubeflow_chisme/exceptions/_generic_charm_runtime_error.py
Extend `GenericCharmRuntimeError` to receive a list of `args` and propagate these to the `BaseException` initialisation.
> feat: Extend GenericCharmRuntimeError with args

- src/charmed_kubeflow_chisme/kubernetes/README.md
- src/charmed_kubeflow_chisme/kubernetes/_kubernetes_resource_handler.py
- src/charmed_kubeflow_chisme/types/__init__.py
- src/charmed_kubeflow_chisme/types/_lightkube.py
- tests/integration/test_kubernetes.py
- tests/unit/test_kubernetes.py
* Rename the `child_resource_types` `KubernetesResourceHandler` field to `resource_types`
* Convert it to a set to ensure that the elements it contains are unique and allow for efficient membership checks
* Make necessary changes to tests
> feat: Store managed K8s resource types in a set

- setup.cfg
- src/charmed_kubeflow_chisme/kubernetes/_kubernetes_resource_handler.py
- src/charmed_kubeflow_chisme/lightkube/batch/_many.py
Capture `ApiErrors` when attempting to delete K8s resources and provide an option to ignore 404 errors, since they don't affect the deletion. Catch everything else and raise it at the end, after deletion is attempted for all detected resources. 
Add logging to the `apply_many` and `delete_many` helpers.
> feat: Add error handling for deleting resources

- tox.ini
publish should be done via instruction in [README](https://github.com/canonical/charmed-kubeflow-chisme#publishing-to-pypi)
> remove tox publish

- src/charmed_kubeflow_chisme/status_handling/__init__.py
- src/charmed_kubeflow_chisme/status_handling/_set_and_log_status.py
- tests/unit/test_status_handling.py
- Add a set_and_log_status(unit, logger, status) function to set and log changes  in the unit's status. This function was initially introduced in [istio-pilot charm](https://github.com/canonical/istio-operators/blob/047ed3513e2098560da7cfd4f10b01f6495c54e7/charms/istio-pilot/src/charm.py#L724-L741).
- Unit test the function
Note that there was the argument that logging the status' history is something we shouldn't do and that should be handled by `Juju` itself but ATM this is not happening.
> feat: Add set_and_log_status()

- src/charmed_kubeflow_chisme/components/charm_reconciler.py
- src/charmed_kubeflow_chisme/components/component_graph.py
The status prioritizer previously would report an UnknownStatus when it had no components to report statuses.  UnknownStatus is a readonly status in Juju so this is not appropriate.  This commit changes Prioritizer to identify when it has no components and instead return ActiveStatus (since a Prioritizer without anything is effectively Active).
> fix `Prioritizer` to avoid setting `UnknownStatus` when empty

- pyproject.toml
- src/charmed_kubeflow_chisme/components/__init__.py
- src/charmed_kubeflow_chisme/components/charm_reconciler.py
- src/charmed_kubeflow_chisme/components/component_graph.py
- src/charmed_kubeflow_chisme/components/component_graph_item.py
- src/charmed_kubeflow_chisme/kubernetes/__init__.py
- src/charmed_kubeflow_chisme/kubernetes/_kubernetes_resource_handler.py
- src/charmed_kubeflow_chisme/types/__init__.py
- tests/unit/components/test_charm_reconciler.py
- tests/unit/components/test_component_graph.py
- tests/unit/test_kubernetes.py
- tests/unit/test_status_handling.py
Previously, isort was using its default line_length=79, whereas all other linting was done with line_length=99.  This commit fixes the setting and reformates any files affected.
> fix isort line_length setting

- src/charmed_kubeflow_chisme/components/__init__.py
- src/charmed_kubeflow_chisme/components/pebble_component.py
- tests/unit/components/test_pebble_component.py
adds a lazy-rendering version of the ContainerFileTemplate to allow for inputs to be passed as callables rather than literal values.  
Closes #89
Since this introduces a `LazyContainerFileTemplate` and then modifies the previous `ContainerFileTemplate` to use the new lazy version as a backend, there's a chance of regressions that break the original `ContainerFileTemplate`.  Tests for this were added, and [this pvcviewer draft PR](https://github.com/canonical/pvcviewer-operator/pull/30) was created to regression test this chisme PR branch.
> add pebble_components.LazyContainerFileTemplate

- setup.cfg
After #98 was merged, we're bumping the version from 0.3.0 to 0.4.0.
> Bump version to 0.4.0

- src/charmed_kubeflow_chisme/testing/cos_integration.py
- tests/unit/testing/test_cos.py
To avoid relying on a mutable message, this commit removes the assertion done for checking the status of the grafana-agent-k8s charm after being deployed.
Fixes #104
> fix: remove assertion of BlockedStatus message

- .github/workflows/tests.yaml
Part of canonical/bundle-kubeflow#944
> ci: use juju 3.4/stable instead of 3.5/stable

- src/charmed_kubeflow_chisme/testing/cos_integration.py
- tests/unit/testing/test_cos.py
Running `cat metadata.yaml` from first charm unit and get charm_name from stdout.
fixes: #113
> Get charm_name from charm metadata.yaml

- setup.cfg
Releasing new version of chisme, so the `assert_grafana_dashboards` can be used.
> bump version to 0.4.2

- src/charmed_kubeflow_chisme/testing/README.md
- src/charmed_kubeflow_chisme/testing/cos_integration.py
- tests/unit/testing/test_cos.py
Retry assert_metrics_endpoint() by default in order to avoid failing tests due to the metrics endpoint not being scrapable yet.
Part of canonical/metacontroller-operator#138
> feat: Retry assert_metrics_endpoint() by default

- src/charmed_kubeflow_chisme/testing/cos_integration.py
In one of CI I saw this line:
`FAILED tests/integration/test_charm.py::test_metrics_enpoint - AssertionError: target for tensorboard-controller is not in down` and it's hard to understand.
> Update error message, when target state is not "up"

- setup.cfg
Release 0.4.4 with changes:
* https://github.com/canonical/charmed-kubeflow-chisme/pull/124
* https://github.com/canonical/charmed-kubeflow-chisme/pull/121
> chore: bump version to 0.4.4

- src/charmed_kubeflow_chisme/components/__init__.py
- src/charmed_kubeflow_chisme/components/pebble_component.py
- tests/unit/components/test_pebble_component.py
This PR adds to the list of events that are observed by the `PebbleServiceComponent`. The following events are added:
- [pebble_check_failed](https://ops.readthedocs.io/en/latest/state-transition-testing.html#ops.testing.CharmEvents.pebble_check_failed)
- [pebble_check_recovered](https://ops.readthedocs.io/en/latest/state-transition-testing.html#ops.testing.CharmEvents.pebble_check_recovered)
This will be useful while writing the Github Profiles Automator charm, see https://github.com/canonical/github-profiles-automator/issues/13
> Add more events to PebbleServiceComponent

- src/charmed_kubeflow_chisme/components/pebble_component.py
- tests/unit/components/test_pebble_component.py
Closes #133 
This is a simple fix that changes the defined type of `permissions` from `str` to `int`. Additionally, the unit tests are updated to reflect this change
> Fix type for `permissions` field in LazyContainerFileTemplate and ContainerFileTemplate

- src/charmed_kubeflow_chisme/lightkube/batch/_many.py
- src/charmed_kubeflow_chisme/testing/README.md
- src/charmed_kubeflow_chisme/testing/__init__.py
- src/charmed_kubeflow_chisme/testing/charm_spec.py
* Add CharmSpec data class to enable defining charms that need to be
deployed during tests.
* Add generate_context_from_charm_spec_dict() to extracting context from
a dict with CharmSpec objects, in order to render bundle.yaml.j2
files.
Ref canonical/bundle-kubeflow/issues/1256
Tests fail due to #139, which will be addressed separately.
> feat(tests): Add CharmSpec dataclass and helper

- setup.cfg
Release 0.4.7 with changes from
* #138 (f3009cc9dd05e5e1f3c97bb769e7f2846ca22dee)
WRT effort in canonical/bundle-kubeflow#1256.
> chore: bump version to 0.4.7

- tests/integration/test_cos.py
- tox.ini
Refactor integration tests to fetch alert rules dynamically. This ensures that alert rules being checked are up-to-date and simulate a real-world scenario, since `assert_alert_rules` is meant to be used in charm repositories. This is achieved by:
1. Downloading the `.charm` artifact
2. Extracting it
3. Using `get_alert_rules()` on the extracted path.
Addresses part 1 of #139
* Integration tests are expected to fail due to part 2 of #139 which is fixed #141. We can see though that the fix works by taking a look at the alert rules being compared in the error messsage.
* Linting is fixed in #138.
> fix(tests): Fetch alert rules dynamically

- src/charmed_kubeflow_chisme/testing/cos_integration.py
assert_alert_rules() returns True if the provided alert rules consist a subset of the alert rules in the data bag. This is needed since `prometheus_scrape` library injects some default alert rules on the fly after canonical/prometheus-k8s-operator#660.
Address point 2 of #139
Linting is fixed in #138.
> fix: assert_alert_rules returns True if rules are a subset

- setup.cfg
Release 0.4.8 with changes from
* #140
* #141
* #144
> chore: bump version to 0.4.8

- .github/workflows/publish.yaml
Update as we were seeing the same error as in
pypa/gh-action-pypi-publish#354 when trying to release.
> chore(ci): bump gh-action-pypi-publish to 1.12.4

- setup.cfg
Release 0.4.9 since 0.4.8 and 0.4.7 failed to be released
due to CI issues. The CI should have been fixed in #146
> chore: bump version to 0.4.9

- tests/integration/test_cos.py
Closes https://github.com/canonical/charmed-kubeflow-chisme/issues/152
1. Pin the channel and base for the `blackbox-exporter-k8s` charm, used in integration tests
> fix: pin blackbox-exporter-k8s channel and base to fix tests

- src/charmed_kubeflow_chisme/testing/cos_integration.py
- tests/integration/test_cos.py
- tests/unit/testing/test_cos.py
Reference issue: #155
This PR simply updates the default channel for all observability charms to "1/stable", since `latest/stable` has been deprecated. This includes:
- `grafana-agents-k8s` in `deploy_and_assert_grafana_agent()`
- `blackbox-exporter-k8s` in `tests/integration/test_cos.py`
> fix: Update default channel for observability charms
