canonical/charmed-kubeflow-chisme

README.md
src/k8s_resource_handler/exceptions/README.md
src/k8s_resource_handler/kubernetes/README.md
src/k8s_resource_handler/lightkube/README.md
src/k8s_resource_handler/status_handling/README.md
src/k8s_resource_handler/types/README.md

Update README.md, add README.md files to subfolders

---

tox.ini

Add publishing to tox.ini

---

README.md
src/charmed_kubeflow_chisme/pebble/README.md
src/charmed_kubeflow_chisme/pebble/__init__.py
src/charmed_kubeflow_chisme/pebble/_update_layer.py
tests/test_pebble.py
tox.ini

The update_layer function is repeated across many charms. This PR adds this function to chisme to be shared across all charms in the future.

shared update layer handler

---

.github/workflows/ci.yaml

[skip ci] git-xargs programmatic commit

ci: Replace ubuntu-latest with ubuntu-20.04

---

src/charmed_kubeflow_chisme/kubernetes/README.md

This commit attempts to flesh out more usage patterns for the KubernetesResourceHandler.  Not sure if it quite hits the mark though - feels like it could be massaged more

doc: Add some example usage patterns for KRH

---

src/charmed_kubeflow_chisme/kubernetes/_kubernetes_resource_handler.py
tox.ini

https://github.com/canonical/charmed-kubeflow-chisme/issues/35
Summary of changes:
- Exposed `force` parameter in apply() and relayed it to apply_many()

fix: exposed force parameter

---

setup.cfg

Summary of changes:
- Bumped version to 0.0.6

chore: bump version to 0.0.6

---

setup.cfg

feat: version bump 0.0.6->0.0.7

---

setup.cfg

Please merge after #46 and IFF there is any other change you think should be included in the next release.

feat: version bump 0.0.7->0.0.8

---

.github/workflows/gh-release.yaml
.github/workflows/publish.yaml
README.md
setup.cfg

update docs
bump package version
update files to be attached to GH release

minor CI change

---

setup.cfg

Version bump in setup.cfg file

feat: version bump 0.0.8->0.0.9

---

src/charmed_kubeflow_chisme/kubernetes/_kubernetes_resource_handler.py

* Check for conflicts when applying K8s resources and report them appropriately
* Use `force` by default when applying K8s resources

feat: Handle conflicts when applying K8s resources

---

README.md

reorder bullets in readme contents to be alphabetical

---

README.md
src/charmed_kubeflow_chisme/testing/__init__.py
src/charmed_kubeflow_chisme/testing/serialized_data_interface.py

Adds helpers for mocking SDI-backed relations and their data during unit tests.

feat: add tools for testing SerializedDataInterface-backed relations

---

.github/workflows/tests.yaml

ci: update microk8s to 1.25

---

setup.cfg

when this is merged, we should create a tag 0.2.1 and push it to the repo to initiate the release procedure

bump package version for new release

---

setup.cfg

when this is merged, we should create a tag 0.3.0 and push it to the repo to initiate the release procedure

bump package version to 0.3.0

---

README.md
src/charmed_kubeflow_chisme/rock/README.md
src/charmed_kubeflow_chisme/rock/_check_rock.py

chore: fix rocks terminology

---

.github/workflows/tests.yaml

Part of canonical/bundle-kubeflow#903

ci: bump microk8s 1.25 -> 1.29

---

setup.cfg

chore: bump 0.4.0 -> 0.4.1

---

src/charmed_kubeflow_chisme/testing/cos_integration.py
tests/unit/testing/test_cos.py

Add filter for port and path in `_get_targets_from_grafana_agent` function, so it's possible to tests charms with multiple metrics port and paths.
fixes: #119

Filter targets with port and path

---

setup.cfg

CI fails due to #125
Closes #127

fix: Pin httpx due to gtsystem/lightkube#78

---

tests/integration/test_cos.py

fix(tests): Update expected alert rules

---

tox.ini

fix(lint): pin snowballstemmer due to snowballstem/snowball#229

---

src/charmed_kubeflow_chisme/components/serialised_data_interface_components.py

Resolves https://github.com/canonical/charmed-kubeflow-chisme/issues/149 and https://github.com/canonical/charmed-kubeflow-chisme/issues/150
1. Use [`model.relations[...][0]`](https://github.com/canonical/operator/blob/010561f00d4c97b87072626feee591b84a19850d/ops/model.py#L165) instead of [`model.get_relation(...)`](https://github.com/canonical/operator/blob/010561f00d4c97b87072626feee591b84a19850d/ops/model.py#L248) for getting the information about a relation
2. Print the exception's traceback, when handling a generic `Exception`
NOTE: I've also tried the changes from this PR with MinIO in https://github.com/canonical/minio-operator/pull/233#pullrequestreview-2899900282 and it worked as expected.

fix: handle multiple relations for endpoint in sdi-provider component
